buildscript {
    repositories {
    }

    dependencies {
    }
}
apply plugin: 'com.android.application'

repositories {
    maven { url 'https://zendesk.artifactoryonline.com/zendesk/repo' }
    // For drawing a circular tile with letter inside it, like in contacts
    maven { url 'http://dl.bintray.com/amulyakhare/maven' }
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.eventshigh.nearme.app"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 295
        versionName "2.9.5"



    }
    signingConfigs {
        debug {
            storeFile file('../debug.keystore')
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile(name:'volley-release', ext:'aar')


    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:support-v4:23.2.1'
    compile 'com.android.support:cardview-v7:23.2.1'
    compile 'com.android.support:recyclerview-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'


    compile 'it.sephiroth.android.library.imagezoom:imagezoom:2.2.2'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    compile 'io.branch.sdk.android:library:1.10.8'

}

apply plugin: 'com.google.gms.google-services'
