buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.14.4'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.eventshigh.nearme.app"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 38
        versionName "0.3.4"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':volley')

    // Ideally, we should change the dependency to following but its not working
    // as expected. We need to revisit at later point.
    // compile 'com.google.android.gms:play-services-base:6.5.87'
    // compile 'com.google.android.gms:play-services-location:6.5.87'
    // compile 'com.google.android.gms:play-services-maps:6.5.87'

    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-v4:21.0.3'

    compile 'com.github.amlcurran.showcaseview:library:5.0.0'
    compile 'com.amplitude:android-sdk:1.4.3'
    compile 'it.sephiroth.android.library.imagezoom:imagezoom:1.0.5'
    compile 'fr.nicolaspomepuy:discreetapprate:2.0.3@aar'

//    compile('com.twitter.sdk.android:twitter:1.1.1@aar') {
//        transitive = true;
//    }
    compile('com.crashlytics.sdk.android:crashlytics:2.2.0@aar') {
        transitive = true;
    }
}
